---
info:
  base_dir: "/home/user/dotfiles"
ops:
  zsh:
    - op:   "substitute"
      file: "conf/zshrc"
      from: "##-ZSHROOT-##"
      to:   "/home/user/dotfiles/lib/zsh"
    - op:   "link"
      from: "conf/zshrc"
      to:   ".zshrc"
